version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say CircleCI"
          command: "echo Hello, CircleCI!"

  say-byebye:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say CircleCI"
          command: "echo byebye"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - say-byebye
